# Generated by Django 4.0 on 2022-03-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
