# Generated by Django 4.0 on 2022-03-13 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogmodel_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
