# Generated by Django 4.0 on 2022-03-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blogmodel_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='host',
            new_name='author',
        ),
    ]
