# Generated by Django 4.0 on 2022-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_rename_host_blogmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
