# Generated by Django 4.0 on 2022-03-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_blogmodel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='comment',
        ),
        migrations.CreateModel(
            name='commentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('blogmod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogmodel')),
            ],
        ),
    ]
