# Generated by Django 4.0 on 2022-03-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_commentmodel_blogmod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='blogmod',
            new_name='blogmodel',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
