# Generated by Django 4.0 on 2022-03-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogapp', '0010_blogmodel_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Newpost',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='summary',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
